#
# REF:
#   1. Nushell build strategy: https://github.com/nushell/nushell/blob/main/.github/workflows/release.yml
#
name: Create Release Draft

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

defaults:
  run:
    shell: bash

jobs:
  standard:
    name: Build-and-deploy

    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - riscv64gc-unknown-linux-gnu
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: x86_64-apple-darwin
            os: macos-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: x86_64-pc-windows-msvc
            extra: "bin"
            os: windows-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: x86_64-pc-windows-msvc
            extra: msi
            os: windows-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: aarch64-pc-windows-msvc
            extra: "bin"
            os: windows-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: aarch64-pc-windows-msvc
            extra: msi
            os: windows-latest
            target_rustflags: ""
            python-version: "3.x"
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            target_rustflags: ""
            python-version: "3.x"
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
            target_rustflags: ""
            python-version: "3.x"
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
            target_rustflags: ""
            python-version: "3.x"
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-20.04
            target_rustflags: ""
            python-version: "3.x"
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
            target_rustflags: ""
            python-version: "3.x"

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set environment variables
        run: |
          echo "PYO3_PYTHON=python" >> $GITHUB_ENV

      - name: Add Python to PATH
        run: echo "$pythonLocation/bin" >> $GITHUB_PATH
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.1/x64

      - name: Print debugging information
        run: |
          python --version
          which python
          echo "PATH: $PATH"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Extract version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Release Tgs Binary
        run: bash .github/workflows/release-pkg.sh
        env:
          BIN_NAME: ${{ matrix.bin_name }}
          RELEASE_TYPE: standard
          OS: ${{ matrix.os }}
          REF: ${{ github.ref }}
          TARGET: ${{ matrix.target }}
          _EXTRA_: ${{ matrix.extra }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}

      - name: Build archive
        shell: bash
        run: |
          binary_name="<BINARY_NAME>"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET }}
